global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'send-to-both'

receivers:
  - name: 'send-to-both'
    slack_configs:
      - send_resolved: true
        api_url:
        channel: '#alerts'  
        username: 'SecureBank Alerts'
        title: '{{ .CommonAnnotations.summary }}'
        text: |-
          *ğŸš¨ Alert:* {{ .CommonAnnotations.description }}
          *ğŸ”§ Status:* {{ .Status }}
          *ğŸ“ Instance:* {{ .CommonLabels.instance }}
          *ğŸ”¥ Severity:* {{ .CommonLabels.severity }}
          {{ with (index .Alerts 0) }}
          *â° Time:* {{ .StartsAt }}
          {{ end }}

    webhook_configs:
      - url: 'http://webhook-service.monitoring.svc.cluster.local/alert'
        send_resolved: true
